apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- crossplane-addons.yaml
- crossplane-configurations.yaml
- crossplane.yaml
- external-secrets.yaml
- grafana-operator.yaml
- traefik.yaml
- victoria-metrics-operator.yaml
