apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- authentik.yaml
- cnpg-system.yaml
- crossplane.yaml
- external-secrets.yaml
- grafana-operator.yaml
- grocy.yaml
- keycloak.yaml
- kyverno.yaml
- monitoring.yaml
- observability.yaml
- ocis.yaml
- robusta.yaml
- traefik.yaml
- trivy-system.yaml
- velero.yaml
- weaveworks.yaml
- victoria-metrics.yaml
